"""Charta Nirmāṇa — AI/ML code generator for Charta SPOK.

Nirmāṇa (निर्माण) berarti "penciptaan/pembentukan". Modul ini menerjemahkan
perintah SPOK yang berkaitan dengan kecerdasan buatan menjadi kode Python yang
dapat dijalankan, dengan fallback ke scikit-learn bila dependensi opsional
tidak terpasang.
"""

from __future__ import annotations

import re
from typing import Any


AI_PREDICATES: set[str] = {
    "MUAT_MODEL",
    "LATIH_MODEL",
    "INFERENSI",
    "SIAPKAN_DATA",
    "EVALUASI_MODEL",
    "SIMPAN_MODEL",
    "PREDIKSI",
}

# Map SPOK predicate -> generator of Python code lines given the sentence data.
_AI_CODE: dict[str, Any] = {
    "SIAPKAN_DATA": lambda d: [
        "# SPOK: SISTEM SIAPKAN_DATA DATASET",
        "import pandas as pd",
        "from sklearn.model_selection import train_test_split",
        "",
        "df = pd.read_csv('charta_dataset.csv')",
        "X = df.drop(columns=['target'])",
        "y = df['target']",
        "X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)",
    ],
    "MUAT_MODEL": lambda d: [
        "# SPOK: SISTEM MUAT_MODEL MODEL",
        "import joblib",
        "model = joblib.load('charta_model.pkl')",
    ],
    "LATIH_MODEL": lambda d: [
        "# SPOK: SISTEM LATIH_MODEL MODEL",
        "from sklearn.ensemble import RandomForestClassifier",
        "",
        "model = RandomForestClassifier(n_estimators=100, random_state=42)",
        "model.fit(X_train, y_train)",
    ],
    "INFERENSI": lambda d: [
        "# SPOK: SISTEM INFERENSI DATASET",
        "predictions = model.predict(X_test)",
    ],
    "PREDIKSI": lambda d: [
        "# SPOK: SISTEM PREDIKSI HASIL",
        "print('Predictions:', predictions)",
    ],
    "EVALUASI_MODEL": lambda d: [
        "# SPOK: SISTEM EVALUASI_MODEL MODEL",
        "from sklearn.metrics import accuracy_score",
        "",
        "accuracy = accuracy_score(y_test, predictions)",
        "print('Akurasi:', accuracy)",
    ],
    "SIMPAN_MODEL": lambda d: [
        "# SPOK: SISTEM SIMPAN_MODEL MODEL",
        "import joblib",
        "joblib.dump(model, 'charta_model.pkl')",
    ],
}


def is_ai_command(predicate: str) -> bool:
    return predicate in AI_PREDICATES


def to_python(data: dict[str, Any]) -> str:
    """Return a Python block for an AI SPOK sentence."""
    predicate = data.get("predicate", "")
    generator = _AI_CODE.get(predicate)
    if generator is None:
        return f"# SPOK AI: {data.get('subject')} {predicate} {data.get('object')}"
    return "\n".join(generator(data))


def build_ai_script(spok_lines: list[dict[str, Any]], name: str = "ai_module") -> str:
    """Assemble a runnable Python script from a sequence of AI SPOK instructions."""
    lines = [f"# Generated by Charta Nirmāṇa from {name}", ""]
    for item in spok_lines:
        block = to_python(item)
        if block:
            lines.extend(block.splitlines())
            lines.append("")
    return "\n".join(lines)
