// Generated by Charta runtime; review before attaching to a live account.
// MetaTrader 5 reads Charta decisions via the ZeroMQ bridge (charta_mt5_bridge.py).
#property strict
#include <charta_bridge.mqh>
input string ChartaTopic = "charta/signals";

void OnTick()
{
   string signal = ChartaRequest(ChartaTopic);
   if(StringLen(signal) == 0) return;
   // Charta IR instructions are intentionally explicit for review.
   // AG1 SPOK: BOT_RBT KIRIM_PESANAN ORDER DI_METATRADER5
   ProcessChartaSignal(signal, "AG1");
   // AG2 SPOK: BOT_RBT TUTUP_PESANAN ORDER DI_METATRADER5
   ProcessChartaSignal(signal, "AG2");
   // AG3 SPOK: BOT_RBT HITUNG_MA ASET_RISIKO_75 DI_METATRADER5
   ProcessChartaSignal(signal, "AG3");
   // AG4 SPOK: SISTEM SAAT_TIK PASAR OTOMATIS_24JAM
   ProcessChartaSignal(signal, "AG4");
   // AG5 SPOK: SISTEM BACA_PASAR DATA DI_METATRADER5
   ProcessChartaSignal(signal, "AG5");
}
