// Generated by Charta runtime; review before attaching to a live account.
// MetaTrader 5 reads Charta decisions via the ZeroMQ bridge (charta_mt5_bridge.py).
#property strict
#include <charta_bridge.mqh>
input string ChartaTopic = "charta/signals";

void OnTick()
{
   string signal = ChartaRequest(ChartaTopic);
   if(StringLen(signal) == 0) return;
   // Charta IR instructions are intentionally explicit for review.
   // AG1 SPOK: SISTEM KELAS NAMA OTOMATIS
   ProcessChartaSignal(signal, "AG1");
   // AG2 SPOK: SISTEM MEMBACA DATA OTOMATIS
   ProcessChartaSignal(signal, "AG2");
   // AG3 SPOK: SISTEM MENAMPILKAN PESAN OTOMATIS
   ProcessChartaSignal(signal, "AG3");
   // AG4 SPOK: SISTEM MENYIMPAN NILAI SECARA_AMAN
   ProcessChartaSignal(signal, "AG4");
   // AG5 SPOK: SISTEM ULANG DAFTAR OTOMATIS
   ProcessChartaSignal(signal, "AG5");
}
