# Generated by Charta runtime from ai.cht
# SPOK: SISTEM SIAPKAN_DATA DATASET
import pandas as pd
from sklearn.model_selection import train_test_split

df = pd.read_csv('charta_dataset.csv')
X = df.drop(columns=['target'])
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
# SPOK: SISTEM LATIH_MODEL MODEL
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train, y_train)
# SPOK: SISTEM INFERENSI DATASET
predictions = model.predict(X_test)
# SPOK: SISTEM EVALUASI_MODEL MODEL
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, predictions)
print('Akurasi:', accuracy)
# SPOK: SISTEM PREDIKSI HASIL
print('Predictions:', predictions)
# SPOK: SISTEM SIMPAN_MODEL MODEL
import joblib
joblib.dump(model, 'charta_model.pkl')
